import Head from "next/head";
import Image from "next/image";
import BasicLayout from "../components/molecules/basic_layout";
import styled from "styled-components";
import mainPagePic from "../public/main_page_photo.png";

const MainSection = styled.main`
  display: grid;
  grid-template-columns: 1fr 2fr;
`;

const Title = styled.h1`
  font-size: 48px;
  color: #0f5057;
  margin-bottom: 0;
`;

const Description = styled.p`
  max-width: 350px;
`;

const ImageWrapper = styled.div`
  position: relative;
  justify-self: center;
`;

const TextSection = styled.div`
  display: flex;
  flex-direction: column;
  align-self: center;
`;

export default function Home() {
  return (
    <BasicLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainSection>
        <TextSection>
          <Title>
            Zyskaj radość <br />
            Dzieląc się z innymi
          </Title>

          <Description>
            Sleep on dog bed, force dog to sleep on floor. Cats are fats i like
            to pets them they like to meow back damn that dog but bawl under
            human beds
          </Description>
        </TextSection>

        <ImageWrapper>
          <Image
            style={{
              objectFit: "contain",
              width: "100%",
              height: "100%",
            }}
            src={mainPagePic}
          />
        </ImageWrapper>
      </MainSection>
    </BasicLayout>
  );
}
