import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import MainMenu from "../components/molecules/main_menu";
import BasicLayout from "../components/molecules/basic_layout";

export default function Home() {
  return (
    <BasicLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Image width="100" height="100" src="/main_page_photo.webp"></Image>
    </BasicLayout>
  );
}
